name: vercel

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]
    workflow_dispatch:

env:
    VITE_API_KEY: ${{ secrets.VITE_API_KEY }}
    VITE_AUTH_DOMAIN: ${{ secrets.VITE_AUTH_DOMAIN }}
    VITE_PROJECT_ID: ${{ secrets.VITE_PROJECT_ID }}
    VITE_STORAGE_BUCKET: ${{ secrets.VITE_STORAGE_BUCKET }}
    VITE_MESSAGING_SENDER_ID: ${{ secrets.VITE_MESSAGING_SENDER_ID }}
    VITE_APP_ID: ${{ secrets.VITE_APP_ID }}
    VITE_MEASUREMENT_ID: ${{ secrets.VITE_MEASUREMENT_ID }}

jobs:
    build:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v1
              with:
                  node-version: 16.x
            - run: npm ci
            - run: npm run build
            - name: copy file
              uses: canastro/copy-file-action@master
              with:
                  source: "./vercel.json"
                  target: "./build/vercel.json"
            - name: Deploy to Vercel Action
              uses: BetaHuhn/deploy-to-vercel-action@v1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
                  WORKING_DIRECTORY: "./build"
