name: vercel

on:
    push:
        branches:
            - main
    pull_request:
        types: [opened, synchronize, reopened]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[skip ci]')"
        steps:
            - uses: actions/checkout@v2

            - name: Setup Bun Runtime
              uses: antongolub/action-setup-bun@v1 # or @v1.x.x
              with:
                  cache: true
                  cache-bin: true

            - name: Install dependencies
              run: bun i

            - name: Build svelte SSR
              run: bun run build

            - name: copy vercel.json
              uses: canastro/copy-file-action@master
              with:
                  source: "./vercel.json"
                  target: "./build/vercel.json"

            - name: Deploy to Vercel
              uses: BetaHuhn/deploy-to-vercel-action@v1
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
                  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
                  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
                  WORKING_DIRECTORY: "./build"
